version: "3"

services:

  adminer:
    image: adminer:latest
    restart: always
    container_name: adminer
    ports:
      - 4444:8080
    networks:
      - default

  app:
    build:
      context: ./
      dockerfile: .docker/local/Dockerfile
    restart: always
    container_name: app
    environment:
      - PORT=80
    ports:
      - "80:80"
    networks:
      - default
    volumes:
      - ./:/var/www

volumes:
  web-app:
    driver: local
  mysql-data:
    driver: local

networks:
  default:
